export * from "./getMangaById";
export * from "./getMangaByTitle";
export * from "./getMangaCharacters";
export * from "./getMangaListByGenre";
export * from "./getMangaPopular";
export * from "./getMangaRecommendations";
export * from "./getMangaRelations";
export * from "./getMangaStaff";
export * from "./getMangaTrending";
